# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 333648fa252b38348cbd13177ed972f854e8c5651b48c076ad724043129e992adbb6720e24636da5e1d7b6863ab52a06df9629e0d93860a910a8fc0c19f4a4f7

test:
  secret_key_base: a2596ba20409c0f2d1d4aa04fd33e38f2404821a2727768b219579fe7ef34979387fecdba91fd3edbb95ca8a87fa7f6f64612f9a9e1d616299ffd6d108944b84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
