@startuml table


package main_db as ext <<Database>> {

  entity contests {
    + id
    --
    cont_id [PK]
    name
    text
    start_date
    cont_type [FK]
    term
    users
    input_template
    data
    view
    inputs
  }


  entity UC_relate {
    + id
    --
    user_id [FK]
    cont_id [FK]

    login_token
  }

  entity user {
    + id
    --
    user_id [PK]
    password (hashed)
  }

  entity cont_types {
  + id
  --
  cont_type [PK]
  }
}


user |o--o{ UC_relate
UC_relate }o-ri-o| contests
cont_types |o--o{ contests

@enduml
